name: geo_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  connectivity_plus: ^2.3.7
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  expressions: ^0.2.4
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  fluttertoast: ^8.0.9
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  lottie: ^1.4.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.1

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.3

flutter:

  uses-material-design: true
  # assets:
  # fonts:
